create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  player_name text not null default 'Strategy learner',
  city text not null default 'Almaty',
  xp integer not null default 80,
  streak integer not null default 0,
  pro_active boolean not null default false,
  board_skin text not null default 'classic',
  progress jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.game_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  player_name text not null,
  city text not null,
  score integer not null,
  result text not null,
  mode_label text not null,
  level_title text not null,
  focus text not null,
  move_count integer not null default 0,
  moves jsonb not null default '[]'::jsonb,
  snapshots jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.leaderboard_entries (
  user_id uuid primary key references auth.users(id) on delete cascade,
  player_name text not null,
  city text not null,
  xp integer not null default 0,
  level_title text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.skin_unlocks (
  user_id uuid references auth.users(id) on delete cascade,
  skin_id text not null,
  source text not null default 'pro_preview',
  created_at timestamptz not null default now(),
  primary key (user_id, skin_id)
);

alter table public.profiles enable row level security;
alter table public.game_reviews enable row level security;
alter table public.leaderboard_entries enable row level security;
alter table public.skin_unlocks enable row level security;

drop policy if exists "profiles are readable by owner" on public.profiles;
create policy "profiles are readable by owner"
  on public.profiles for select
  using (auth.uid() = user_id);

drop policy if exists "profiles are writable by owner" on public.profiles;
create policy "profiles are writable by owner"
  on public.profiles for insert
  with check (auth.uid() = user_id);

drop policy if exists "profiles are updatable by owner" on public.profiles;
create policy "profiles are updatable by owner"
  on public.profiles for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "reviews are readable by owner" on public.game_reviews;
create policy "reviews are readable by owner"
  on public.game_reviews for select
  using (auth.uid() = user_id);

drop policy if exists "reviews are writable by owner" on public.game_reviews;
create policy "reviews are writable by owner"
  on public.game_reviews for insert
  with check (auth.uid() = user_id);

drop policy if exists "leaderboard is public readable" on public.leaderboard_entries;
create policy "leaderboard is public readable"
  on public.leaderboard_entries for select
  using (true);

drop policy if exists "leaderboard is writable by owner" on public.leaderboard_entries;
create policy "leaderboard is writable by owner"
  on public.leaderboard_entries for insert
  with check (auth.uid() = user_id);

drop policy if exists "leaderboard is updatable by owner" on public.leaderboard_entries;
create policy "leaderboard is updatable by owner"
  on public.leaderboard_entries for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "skin unlocks are readable by owner" on public.skin_unlocks;
create policy "skin unlocks are readable by owner"
  on public.skin_unlocks for select
  using (auth.uid() = user_id);

drop policy if exists "skin unlocks are writable by owner" on public.skin_unlocks;
create policy "skin unlocks are writable by owner"
  on public.skin_unlocks for insert
  with check (auth.uid() = user_id);
